### PR TITLE
Use mmdet2trt specific logger

### PR DESCRIPTION
**Pull request by tehkillerbee**
Use mmdet2trt specific logger to avoid messing up main logging.

### CODE REVIEW

**Comment by grimoire** [comment]
Thanks for the contribution! Can you fix the lint check?

**Comment by grimoire** [comment]
Please fix the lint.
You can run `pre-commit run --all-files` before commit.

**Comment by tehkillerbee** [comment]
Thanks, it should be fixed now.

**Review by grimoire — APPROVED** [review]
LGTM!

**Pull request merged**
