### PR TITLE
added output-bbox-name in getting_started.md without which deepstream…

### PR DESCRIPTION
**Pull request by init-22**
… doesnt work

### CODE REVIEW

**Comment by grimoire** [comment]
Hi,
Is this PR related to https://github.com/grimoire/amirstan_plugin/issues/19 ?
Could you briefly explain this PR?

**Comment by init-22** [comment]
Hello there,
No its not related to amirstan_plugin, I solved that by exporting the lib folder and by passing the entire path to that folder, earlier I just copied the .so file into repo from where I was running that code and exported that particular path because of which it wasn't working.

I was trying to use the converted .engine model in DeepStream and followed the instructions in getting_started.md ie. added parse-bbox-func-name, output-blob-names and custom-lib-path but I was still getting an error as indicating that it cannot understand the last output-blob-name ie classes from the model, which I solved by adding output-bbox-name=boxes

**Comment by grimoire** [comment]
Sure, I will check it later.
Is there any documentation about `output-bbox-name`?  I did not find this property in [here](https://docs.nvidia.com/metropolis/deepstream/dev-guide/text/DS_plugin_gst-nvinfer.html)

**Comment by init-22** [comment]
I also couldn't find it in their documentation, I found out about it in one
of the answers in their forum and then added it to the code.

**Review by grimoire — APPROVED** [review]
I can use my model in deepstream without `output-bbox-name` flag.
Still, it is OK to merge this PR since someone might meet the same problem as your's.
Please let me know if you find any documentation or description about the flag or you have any better solution to solve this in future. Thank you.

**Comment by init-22** [comment]
Hey @grimoire, thanks a lot. Yes, I'll definitely let you know if I find anything related to this in future.

**Pull request merged**
